name: CommandCraft
main: me.supermaxman.commandcraft.CommandCraft
version: 1.0
description: Opens all kinds of awesome
commands:
  craft:
    description: Opens Crafting Table
    usage: craft
  ench:
    description: Opens Enchantment Table
    usage: ench
  end:
    description: Opens your enderchest
    usage: end
  enderchest:
    description: Opens your enderchest
    usage: enderchest
  endchest:
    description: Opens your enderchest
    usage: enderchest